name: S3 Trigger DAG

on:
  repository_dispatch:
    types: [s3-upload-trigger]

jobs:
  trigger-dag:
    runs-on: ubuntu-latest
    env:
      AIRFLOW_BASE_URL: ${{ secrets.AIRFLOW_BASE_URL }}
      AIRFLOW_USERNAME: ${{ secrets.AIRFLOW_USERNAME }}
      AIRFLOW_PASSWORD: ${{ secrets.AIRFLOW_PASSWORD }}
    steps:
      - name: Trigger Airflow DAG via API
        run: |
          FILENAME="${{ github.event.client_payload.filename }}"

          curl -X POST "$AIRFLOW_BASE_URL/api/v1/dags/my_final_etl_dag/dagRuns" \
            -H "Content-Type: application/json" \
            -u "$AIRFLOW_USERNAME:$AIRFLOW_PASSWORD" \
            -d "{
                  \"conf\": {
                    \"filename\": \"$FILENAME\"
                  }
                }"

