name: S3 Trigger DAG

on:
  repository_dispatch:
    types: [s3-upload-trigger]

jobs:
  trigger-dag:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Airflow DAG via API
        run: |
          curl -X POST ${{ secrets.AIRFLOW_BASE_URL }}/api/v1/dags/my_final_etl_dag/dagRuns \
          -H "Content-Type: application/json" \
          -u "${{ secrets.AIRFLOW_USERNAME }}:${{ secrets.AIRFLOW_PASSWORD }}" \
          -d '{
                "conf": {
                  "filename": "${{ github.event.client_payload.filename }}"
                }
              }'
