name: S3 Trigger DAG

on:
  repository_dispatch:
    types: [s3-upload-trigger]

jobs:
  trigger-dag:
    runs-on: ubuntu-latest
    env:
      AIRFLOW_BASE_URL: ${{ secrets.AIRFLOW_BASE_URL }}
      AIRFLOW_USERNAME: ${{ secrets.AIRFLOW_USERNAME }}
      AIRFLOW_PASSWORD: ${{ secrets.AIRFLOW_PASSWORD }}

    steps:
      - name: Get JWT Token from Airflow
        id: get-token
        run: |
          response=$(curl -s -X POST "${AIRFLOW_BASE_URL}/auth/token" \
            -H "Content-Type: application/json" \
            -d "{\"username\":\"${AIRFLOW_USERNAME}\",\"password\":\"${AIRFLOW_PASSWORD}\"}")
          
          token=$(echo $response | jq -r '.access_token')

          echo "::add-mask::$token"
          echo "JWT_TOKEN=$token" >> $GITHUB_ENV

      - name: Trigger Airflow DAG via JWT
        run: |
          FILENAME="${{ github.event.client_payload.filename }}"

          curl -X POST "${AIRFLOW_BASE_URL}/api/v2/dags/my_final_etl_dag/dagRuns" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $JWT_TOKEN" \
            -d "$(jq -n --arg filename "$FILENAME" '{conf: {filename: $filename}}')"
